FROM php:7.4-apache

#Pasta padrão
WORKDIR /var/www/html
#Arquivo a serem copiados para conteiner
COPY index.php /var/www/html/
COPY conexao.php /var/www/html/
#Comandos para instalar
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli

#Configuração da porta
EXPOSE 80